### PR TITLE
The closepath is not part of the count of the elements of the ring

### PR DESCRIPTION
**Pull request by ericfischer**
This isn't sufficient to get polygon writing to work from Tippecanoe, but gets one step closer at least.

### CODE REVIEW

**Comment by joto** [comment]
Can you elaborate on the reasons for your change? The way I see this, the mechanics of ClosePath are internal to the vector tile spec, what matters is the number of vertices on a ring. And every other software I have seen counts the last vertex as part of the number of vertices. So a ring must have at least 4 vertices to be a valid ring (and the last and first must be the same). If you count differently, that's easy to adapt, of course.

/cc @flippmoke

**Comment by ericfischer** [comment]
That is a reasonable API but as far as I can tell is not what the current code does. It sets the LineTo repeat count too high (to the total number of points you specify minus the one MoveTo), so the ClosePath opcode is encoded as the last LineTo repeat rather than a separate operation following the end of the repeats.

This PR is definitely not quite right either, but is the closest I've come to being able to being able to encode polygons correctly with any variation on the loop here: https://github.com/mapbox/tippecanoe/blob/ba102b0ea/mvt.cpp#L314 (The code on my side at this stage has a `closepath` operation at the end of the ring rather than a duplicate of the first point.)

I'm happy to change the code on my side to increase the point count by one and either `set_point` again on the first point or continue to `close_ring` to close it, but neither of these seems to produce features that can then be decoded (either by your decoder or mine).

**Comment by flippmoke** [comment]
I think I agree with @joto here as our assumption of the geometry model is that there is a closing point. 

I think perhaps this is more a documentation issue (if there is one) rather then an issue with our current API and code. The only area where I could see this being a problem is our iterators, which obviously expect a closing point.

**Comment by ericfischer** [comment]
I am fine with the existing API, but there is something wrong in the code unless I am doing something wrong in what looks like a straightforward use of it.

With the top-of-tree `vtzero` and either

```
vtz_feature.add_ring(l - k + 1);
for (size_t m = k; m < l; m++) {
        vtz_feature.set_point(f.geometry[m].x, f.geometry[m].y);
}
vtz_feature.set_point(f.geometry[k].x, f.geometry[k].y);
```

or

```
vtz_feature.add_ring(l - k + 1);
for (size_t m = k; m < l; m++) {
        vtz_feature.set_point(f.geometry[m].x, f.geometry[m].y);
}
vtz_feature.close_ring();
```

I run into this exception trying to create and read back polygons:

```
./tippecanoe -aD -f -o tests/coalesce-id/out/-z1_--coalesce_--reorder.json.check.mbtiles -z1 --coalesce --reorder tests/coalesce-id/in.json
./tippecanoe-decode tests/coalesce-id/out/-z1_--coalesce_--reorder.json.check.mbtiles > tests/coalesce-id/out/-z1_--coalesce_--reorder.json.check.out
libc++abi.dylib: terminating with uncaught exception of type vtzero::geometry_exception: expected command 1 but got 0
```

**Comment by ericfischer** [comment]
Never mind. My whole problem (in this part) was that it doesn't work if you set the feature ID after setting the geometry instead of before.

**Pull request closed without merging**
